version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # React app exposed on port 3000
    volumes:
      - ./frontend:/app  # Mount the frontend folder for live changes
    depends_on:
      - backend  # Ensure frontend waits for backend to be ready
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest  # Use the latest version of MySQL
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"  # Changed from 3306:3306 to 3307:3306
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dbdata:
